### PR TITLE
Add CLI command for cherry-picking PlatformPlatform pull requests to downstream projects

### PR DESCRIPTION
**Pull request by raix**
Introduce a new CLI command to simplify the process of cherry-picking pull requests from PlatformPlatform into downstream projects. This command automates identifying, applying, and verifying changes to ensure consistency and alignment between projects.

The command works as follows:

1. Examines the commit history to identify which pull requests from PlatformPlatform are not yet applied to the downstream project. These are presented in a list for selection.
2. Cherry-picks pull requests one by one, prefixing commit messages with `PlatformPlatform PR ### - ` for tracking. This prefix is also used to determine missing changes in step 1.
3. Builds, tests, and runs static code analysis after each cherry-pick to ensure no issues arise. If a failure occurs, the user is provided with detailed instructions for resolving the problem. Once resolved, the command continues.
4. Pauses when PlatformPlatform pull requests contain instructions for required changes in downstream projects, allowing users to address them before proceeding.
5. Offers an option to prepare a pull request once all selected pull requests are cherry-picked (or if the user stops midway). This generates a detailed pull request description for downstream projects.

CLI Command:

```
Usage:
  pp pull-platformplatform-changes [options]

Options:
  --verbose-logging       Show git command and output
  -a, --auto-confirm      Auto confirm picking all upstream pull-requests
  -r, --resume            Validate current branch and resume pulling updates starting with rerunning 
                          checks
  -s, --run-code-cleanup  Run JetBrains code cleanup of backend (slow)
  -?, -h, --help          Show help and usage information
  ```

### Checklist

- [x] I have added a Label to the pull-request
- [x] I have added tests, and done manual regression tests
- [x] I have updated the documentation, if necessary

### CODE REVIEW

**Comment by tjementum** [comment]
Looking awesome. I will look later today.

**Comment by raix** [comment]
I'm thinking it would be cool with a github action cron job to run the gitbot

Only thing I needed to test is if the current check for existing branch names checks non local branches - if so the script would already exit and wait for the existing branch / pr to be merged.

**Comment by tjementum** [comment]
FYI. I’m still looking at this. It does not fully work with other downstream projects using different merge strategies.

Also, I have historically done amend commits on downstream projects to change the commit title so it’s clear it’s a PlatformPlatform Pull Request. Additionally, I’ve made minor fixes in self-contained systems to have them compile. This makes Git unable to see it’s the same commit, and it loses track of what is already integrated.

Finally, I would like to batch up moving pull requests from PlatformPlatform to downstream projects. If PlatformPlatform has a “bad” merge that would cause a production incident, then all downstream projects will get a production incident, even if there is a fix in PlatformPlatform. I’m not too keen on forcing/recommending downstream projects to always run the latest build form PlatformPlatform.

I’m trying to incorporate these changes and make sure it works with all the downstream projects I have access to. But it might take some time for me to get it just right.

But oh boy, this is great and will save a lot of time when updating downstream projects.

**Comment by ayuksekkaya** [comment]
There is also this github action that I came across if we want to take inspiration or offload this functionality. Just wanted to share:

https://github.com/marketplace/actions/actions-template-sync

**Comment by tjementum** [comment]
> There is also this github action that I came across if we want to take inspiration or offload this functionality.

Thanks Ali. However, I don’t want to automatically update downstream projects build on PlatformPlatform, as this will make me responsible for any problems.

And it will give problems for a big portion of changes in PlatformPlatform. Plus, I don’t want to be locked so I cannot make breaking changes.

I have a version ready that I’ve tested on 2 down stream projects, so I hope to complete it soon.

**Comment by tjementum** [comment]
I was not able to rebase and force push to your repository, so I made a different branch and pull request here: https://github.com/platformplatform/PlatformPlatform/pull/642, which is now merged.

I made a lot of changes, but oh my, this is going to save me, you, and us so much time.

**Pull request closed without merging**
